class Model_Object():
        id=''
        code=''
        Effective=''
        Visibility=''
        Status=''
        History=''
        Screen=''
        Label=''
        Description=''
        Version=''
        Subject=''
        Workflow=''
        Pending=''
        Todo=''
        Object=''
        Secured=''
        Permission=''
        RBP=''
        Criteria=''
        Blocking=''

class Process_Object():
      Heading=''
      Status_sap=''

class Validations_Props():
        code = 'B'
        Effective = 'C'
        Visibility = 'D'
        Status = 'E'
        History = 'F'
        Screen = 'G'
        Label = 'H'
        Description = 'I'
        Version = 'J'
        Subject = 'K'
        Workflow = 'L'
        Pending = 'M'
        Todo = 'N'
        Object = 'O'
        Secured = 'P'
        Permission = 'Q'
        RBP = 'R'
        Criteria = 'S'
        Blocking = 'T'


